app:
  mysql:
    enabled: true
    url: test:J0verm@(141.164.54.150:3306)/micro_book_mall?charset=utf8&parseTime=true&loc=Asia%2FShanghai
    maxIdleConnection: 100
    maxOpenConnection: 130
    connMaxLifetime: 100
