app:
  redis:
    enabled: true
    conn: 141.164.54.150:6379
    dbNum: 8
    password:
    timeout: 3000
    sentinel:
      enabled: false
      master: bookMaster
      nodes: 141.164.54.150:16379
